### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by djsg** [epam/med3web#5]
OS: Windows 10
npm --version:  5.6.0
 node --version: v8.11.3

error:
[14:14:55] Failed to load external module @babel/register
[14:14:55] Requiring external module babel-register

med3web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^
ReferenceError: Unknown plugin "syntax-dynamic-import" specified in "D:\\dajiang\\projects\\FitPU\\Code\\Med3Web\\med3web\\.babelrc" at 0, attempted to resolve relative to "D:\\dajiang\\projects\\FitPU\\Code\\Med3Web\\med3web"
    at D:\dajiang\projects\FitPU\Code\Med3Web\med3web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (D:\dajiang\projects\FitPU\Code\Med3Web\med3web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (D:\dajiang\projects\FitPU\Code\Med3Web\med3web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (D:\dajiang\projects\FitPU\Code\Med3Web\med3web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (D:\dajiang\projects\FitPU\Code\Med3Web\med3web\node_modules\babel-register\lib\node.js:103:45)
    at loader (D:\dajiang\projects\FitPU\Code\Med3Web\med3web\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (D:\dajiang\projects\FitPU\Code\Med3Web\med3web\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Comment by VladislavShubnikov** [comment]
fixed with prev commit  c11c631: modify .babelsrc file. Removed unused plugins
